### ISSUE TITLE
Add moneroaddress.org to the repo description

### ISSUE THREAD

**Issue by slrslr** [moneromooo-monero/monero-wallet-generator#18]
Hello,

at https://moneroaddress.org there is a link to this Github repository, but in this repository You are not claiming ownership of that site by mentioning it in the description of the repository.

Mentioning it can help people verify the moneroaddress.org is indeed result of this github project.

**Comment by satnam** [comment]
Bumping this request to @moneromooo-monero 
Could you please confirm or deny ownership of https://moneroaddress.org?

**Comment by moneromooo-monero** [comment]
I do not own that site. It is maintained by saddambitcoin, who's been long trustworthy.

**Comment by moneromooo-monero** [comment]
The site has been down for a few months now AFAIK, and saddambitcoin has been away for some years.
