### ISSUE TITLE
AEON restore from seed no loner works*

### ISSUE THREAD

**Issue by skironDotNet** [moneromooo-monero/monero-wallet-generator#27]
since Aeon started using 25 words, generated seed 24 word seems to work, but then Aeon generated new 25 words and this is so confusing, you need to update generator to work like monero.

Please add option "generate legacy" to generate 24 words, technically spend and view key to be the same wheteher you generate 24 or 25 words

**Comment by SomaticFanatic** [comment]
Came here to start an issue but realized somebody already did. Moo, is it possible to either remove Aeon functionality altogether or update to Aeon 25-word seeds?

**Comment by moneromooo-monero** [comment]
OK, I'll have a look soon

**Comment by moneromooo-monero** [comment]
Should be fixed now, I can generate aeon wallets and restoring them gives me the original seed.
