### ISSUE TITLE
Add information how to spend monero

### ISSUE THREAD

**Issue by urza** [moneromooo-monero/monero-wallet-generator#4]
Hi,
Could you please add instructions to the HTML page how to spend your monero once you received some to the generated address?

Similarly like https://www.bitaddress.org has paragraph "Spend your bitcoins" in the generated "wallet".

I suppose you can import it into full desktop wallet and make regular transactions from there? Would be great to have that info on the HTML page itself.

Thank you

**Comment by moneromooo-monero** [comment]
This only generates an address, spending is done with some other tool which can import the seed and/or private keys. I'm not planning to add anything to do with spending.
