### ISSUE TITLE
Long term storage?

### ISSUE THREAD

**Issue by urza** [moneromooo-monero/monero-wallet-generator#5]
Hi,
I would like to ask you, is this HTML wallet generator suitable for long term cold storage of Monero? Lets say I would like to save and forget about it? Will I be able to use these in few years? What possible problems may I encounter? Versus saving the full desktop wallet with blockchain to some harddisk and also forgeting about it for some time...?

Thanks

**Comment by moneromooo-monero** [comment]
Assuming there are no bugs, this is suitable for long term storage, yes. This page generates keys, and keys will be able to spend your monero. If keys generated with this page somehow  cease to be usable, it will mean they are unusable in simplewallet as well, and that is not the plan at all.
