### ISSUE TITLE
Getting Tx Private Key from moneroaddress.org

### ISSUE THREAD

**Issue by DODGwinsmile** [moneromooo-monero/monero-wallet-generator#6]
http://xmr.llcoins.net/checktx.html
->This site uses in field 2.: Private Viewkey or Tx Private Key
It might be more secure to use Tx Private Key since it is generated for each transaction than the Private Viewkey which is the master password viewkey.
However moneroaddress.org doesn't offer capabilities atm for Tx Private Key. Any ideas for this?

**Comment by moneromooo-monero** [comment]
My wallet generator just generates wallets, nothing more. It does not do anything with transactions.
