### ISSUE TITLE
Off topic - GPG verification

### ISSUE THREAD

**Issue by jorolin** [moneromooo-monero/monero-wallet-generator#7]
Hi,
I am sorry to bother you, but I am rookie (linux, gpg, github) with no experiences in programming etc... I was not able to verify - "monero-wallet-generator.html.asc" according your instructions.

I have downloaded your signature (moneromooo.asc) and imported it (sudo gpg --import moneromooo.asc). So far, ok.

Then - "You need to get the signature file corresponding to the version of the page you're using." - I have downloaded "monero-wallet-generator.html.asc" from link from your generator page (same content like in your git repository). I have both files in the same directory. So far, ok.

Then - I use command - "sudo gpg --verify monero-wallet-generator.html.asc", but message I got was:

"gpg: Podpis vytvořen So 4. únor 2017, 11:02:33 CET pomocí klíče RSA s ID uživatele 4D6CEFC3
gpg: ŠPATNÝ podpis od "moneromooo-monero <moneromooo-monero@users.noreply.github.com>"

sorry it is in the czech language, translation should be like this:

"gpg: Signature made Sa 4. Feb 2017, 11:02:33 CET using keys RSA with user ID 4D6CEFC3
gpg: BAD signature from "moneromooo-monero <moneromooo-monero@users.noreply.github.com>"

Isn't there any step I missed? Also - when I save the webpage from "https://moneroaddress.org/" - it has a slightly different filename - "Monero offline wallet generator.html" - but I always thought, that name of the file is not important for verification or hash...

I would be grateful if you can help me find out what I am doing wrong...

Thanks

**Comment by moneromooo-monero** [comment]
Hi,

You do not need to run gpg as root.

The filename must be the same as the asc file, minus the ".asc".

The file must be saved EXACTLY. No extra newlines, no Windows CR/LR
changes, etc.

**Comment by blockmeister9** [comment]
What gives? Please advise.

gpg --verify monero-wallet-generator.html.asc
gpg: assuming signed data in `monero-wallet-generator.html'
gpg: Signature made Sat 04 Feb 2017 02:02:33 AM PST using RSA key ID 4D6CEFC3
gpg: Good signature from "moneromooo-monero <moneromooo-monero@users.noreply.github.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 48B0 8161 FBDA DFE3 93AD  FC3E 686F 0745 4D6C EFC3

**Comment by Tahutipai** [comment]
My Issue is similar.  The signature verifies, but I get "WARNING: This key is not certified with a trusted signature!"

Is this a security concern?

(P.S Thankyou for making this OWG!)

$ gpg --verify monero-wallet-generator.html.asc
gpg: assuming signed data in 'monero-wallet-generator.html'
gpg: Signature made Sat 04 Feb 2017 05:02:33 AM EST
gpg:                using RSA key 686F07454D6CEFC3
gpg: Good signature from "moneromooo-monero <moneromooo-monero@users.noreply.github.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 48B0 8161 FBDA DFE3 93AD  FC3E 686F 0745 4D6C EFC3

**Comment by twincacca** [comment]
same here

**Comment by palexande** [comment]
twimcacca, blockmeister9, Tahutipai, I believe that the user doing the verifying has to use gpg to certify that the moneromoo's key is genuine/trusted.  Then you won't get that message.

**Comment by stevesbrain** [comment]
@twincacca @blockmeister9 @Tahutipai As long as you "good signature" as you do in this line:
```
gpg: Good signature from "moneromooo-monero moneromooo-monero@users.noreply.github.com" [unknown]
```

The "WARNING: This key is not certified with a trusted signature" refers only to your local "trust database". This is where you say how well you trust that the key belongs to the person in question. This isn't something necessary for this kind of use case, so as long as you see "Good signature", then you are able to use the download safely.

**Comment by moneromooo-monero** [comment]
This is correct, those warnings are expected. As long as you get the "Good signature" message from the correct key, then you're good.

**Comment by Tahutipai** [comment]
Great, thankyou.  May I suggest it may be beneficial to update the instructions at the bottom of the wallet generator page to include expectation of this message?  Esp. for those new to the process.

As it presently stands, if a new user follows the described process verbatim, then the user receives what appears to be, but is not, an error message of concern.  (especially as we are dealing with funds here)

P.S Thankyou for making this!

**Comment by moneromooo-monero** [comment]
Good idea, I've just done this.

**Comment by gravypig** [comment]
Hi - Total novice in this area so forgive me if I'm coming at this in the wrong way.

I'm following the same procedure as above using Git BASH for Windows to verify the signature. As above no issues with the import of the GPG key; key and address all look fine on the face of it.

My problem is that I actually get a BAD signature returned based on the latest update, even though the RSA Key ID appears to match.

Am I missing something? Or is it genuinely an issue that I am pulling up the Bad Signature?

**Comment by stevesbrain** [comment]
@gravypig I haven't done it via Git BASH on Windows before. Should just need something like Kleopatra (GPG4win) and just load the file + sig in there (doesn't specifically need to be done via Git). An example of what it should look like via my linux though (pulling latest update, verifying signature, and then giving you the sha256sum to verify another way):

```bash
:: [stephen@waddleduck] ~/projects/monero-wallet-generator [git:master]
$ git pull
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 3), reused 10 (delta 3), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/moneromooo-monero/monero-wallet-generator
   c04a4e8..da2e7d9  master     -> origin/master
Updating c04a4e8..da2e7d9
Fast-forward
 monero-wallet-generator.html     | 63 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
 monero-wallet-generator.html.asc | 27 +++++++++++++--------------
 2 files changed, 73 insertions(+), 17 deletions(-)
:: [stephen@waddleduck] ~/projects/monero-wallet-generator [git:master]
$ gpg --verify monero-wallet-generator.html{.asc,}
gpg: Signature made Mon 18 Sep 2017 20:10:30 ACST
gpg:                using RSA key 686F07454D6CEFC3
gpg: Good signature from "moneromooo-monero <moneromooo-monero@users.noreply.github.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 48B0 8161 FBDA DFE3 93AD  FC3E 686F 0745 4D6C EFC3
:: [stephen@waddleduck] ~/projects/monero-wallet-generator [git:master]
$ sha256sum monero-wallet-generator.html
c4d7725e88d583e472f3ea3d93ea1f5a9d60abb4155258eb21ebcf6e9760670b  monero-wallet-generator.html
```

**Comment by gravypig** [comment]
Thanks for the quick reply @stevesbrain - I tried GPG4WIN before moving on to GitBASH, but it didn't seem to recognise the signature file at all so in the end I abandoned the attempt.

As it happens since yesterday I have managed to kind of figure out my problem - I wasn't downloading all the original files direct from the github (specifically the html file).

Previously I was saving the wallet generator html file direct from the following web address -https://moneroaddress.org - and then downloading the signature file from github, which was then returning a BAD signature.

I can only assume someone has taken an early version and dropped it in there, but not updated it to the latest version so now the signatures dont match. Either that or its not legit...

Anyway, all sorted now, thanks again much appreciated!

**Comment by stevesbrain** [comment]
@gravypig No worries - glad you got it all sorted :) Likely the moneroaddress.org link hasn't been updated with the latest file. You could probably grab an old signature from github to check it against if you were curious to see if indeed it wasn't legit!

**Comment by duttrishi72** [comment]
> 
> Hi, You do not need to run gpg as root. The filename must be the same as the asc file, minus the ".asc". The file must be saved EXACTLY. No extra newlines, no Windows CR/LR changes, etc.
> […](#)


Thank you! The CR/LR changes by git on Windows may have been causing issues in my case, which I solved by downloading the code .zip file instead of using `git clone https://github.com/moneromooo-monero/monero-wallet-generator`

**Comment by porssimies** [comment]
I cloned the project and then tried to add PGP signature but the following happens:
> me@pc2:~/t/monero-wallet-generator$ gpg --import monero-wallet-generator.html.asc
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
