### ISSUE TITLE
Add ability to type in your mnemonic seed 

### ISSUE THREAD

**Issue by patoshii** [moneromooo-monero/monero-wallet-generator#9]
currently you can only generate addresses, but what if i have my mnemonic seed and want to reveal my pub/priv addresses? Would be great to add ability to change the input of the mnemonic seed.

thanks

**Comment by moneromooo-monero** [comment]
You might be able to do this with https://xmr.llcoins.net

**Comment by ronohara** [comment]
Using xmr.llcoins.net  means sharing your mnemonic seed with some unknown website which is a seriously bad idea.

Being able to recreate from a local web page on your own system would be much better.

**Comment by moneromooo-monero** [comment]
Fair point. In that case, monero-wallet-cli. This is feature creep for this project, I won't be adding this.

**Comment by jonathancross** [comment]
> Using xmr.llcoins.net means sharing your mnemonic seed with some unknown website which is a seriously bad idea.
> 
> Being able to recreate from a local web page on your own system would be much better.

@ronohara

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

If you scroll to the bottom of that web page, you will see that there are download links.
The web page source is located here on GitHub along with a gpg signature:
https://github.com/luigi1111/xmr.llcoins.net/

Note: the file should signed with the PGP key corresponding to this fingerprint:
8777 AB8F 778E E894 87A2  F8E7 F4AC A018 3641 E010

You will see that Luigi's key is cross-signed with my key.  The same key used to sign this message.
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEEMsk361Pa9SImG35c2FeN+Op8zxsFAmXeD/cACgkQ2FeN+Op8
zxttvgf/ee2cwazJb8lJw8P3fpIqfzMcjXhdpqIFSniG1L4S3ClXBoaQ+2/ew7N6
H/zasBWnKSMKR/jSSHlKMiRYUzCfF0j14O83jERPsteDWicuG54JqJ5Bl9z1b/RQ
oPCzYfsXNZSD0EbIjD7ur1wGp7GBzdxx+xu+yfZQeL0iZQpV7VY2iAocO89NFmh3
dcj7bCa2czyALRTgVY89iHLJVP8qT8+856XhTh6DYCuabzH0JvzCqhET181jIVTs
FcPAUmrXYCSnMvsywoS0WQWSz3acw0QfKO44cBPSJDpwGD6MRz3Hp/Z6XJFWALkw
Y/hbmbiGNxPXP5PTDPt7Cmqng+PrUA==
=/mIF
-----END PGP SIGNATURE-----
```


Links to keys with cross-signatures:

 * https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xf4aca0183641e010
 * https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xc0c076132ffa7695
